# Generated by Django 4.2.2 on 2023-06-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32)),
                ('secondName', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField(max_length=16)),
                ('image', models.ImageField(upload_to='')),
                ('id_number', models.IntegerField()),
                ('gersey_number', models.PositiveIntegerField()),
                ('field_number', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('field', models.TextField()),
                ('division', models.TextField()),
            ],
        ),
    ]
