# Generated by Django 4.2.2 on 2023-07-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersdetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='division',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='field',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
    ]
